# Generated by Django 4.0.5 on 2022-06-26 22:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_content_article_content_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_to),
        ),
    ]
