# Generated by Django 4.0.5 on 2022-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='card_headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
