# Generated by Django 4.0.5 on 2022-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_card_headline_article_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
