# Generated by Django 4.0.5 on 2022-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_tags_remove_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='card_headline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
